#!/usr/bin/env python3
"""
Dynamic Inventory Script for Ansible
File: ansible/inventory/dynamic_inventory.py

This script reads the inventory.json file generated by Terraform
and converts it to Ansible inventory format.

Usage:
    python3 dynamic_inventory.py --list
    python3 dynamic_inventory.py --host <hostname>
"""

import json
import argparse
import os
import sys
from pathlib import Path

class DynamicInventory:
    def __init__(self, inventory_file=None):
        """Initialize with inventory file path"""
        if inventory_file is None:
            # Default locations to check
            script_dir = Path(__file__).parent
            possible_paths = [
                script_dir / "inventory.json",
                script_dir.parent.parent / "terraform" / "inventory" / "inventory.json",
                Path.home() / ".ansible" / "inventory" / "inventory.json",
            ]
            
            for path in possible_paths:
                if path.exists():
                    inventory_file = str(path)
                    break
            
            if inventory_file is None:
                print(f"ERROR: Could not find inventory.json in:\n{chr(10).join(str(p) for p in possible_paths)}", 
                      file=sys.stderr)
                sys.exit(1)
        
        self.inventory_file = inventory_file
        self.inventory = self._load_inventory()
    
    def _load_inventory(self):
        """Load inventory from JSON file"""
        try:
            with open(self.inventory_file, 'r') as f:
                data = json.load(f)
            return data
        except FileNotFoundError:
            print(f"ERROR: Inventory file not found: {self.inventory_file}", file=sys.stderr)
            sys.exit(1)
        except json.JSONDecodeError as e:
            print(f"ERROR: Invalid JSON in inventory file: {e}", file=sys.stderr)
            sys.exit(1)
    
    def get_all_hosts(self):
        """Return all hosts in Ansible inventory format"""
        hosts = {}
        group_vars = {
            "all": {
                "ansible_user": "ubuntu",
                "ansible_ssh_private_key_file": "~/.ssh/terraform_ec2_key.pem",
                "ansible_ssh_common_args": "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null",
                "ansible_connection": "ssh",
                "ansible_port": 22,
            }
        }
        
        if "instances" in self.inventory:
            for instance in self.inventory["instances"]:
                host_name = instance.get("instance_name", "unknown")
                
                # Determine the host IP (prefer public IP)
                host_ip = instance.get("public_ip")
                if host_ip == "N/A" or not host_ip:
                    host_ip = instance.get("private_ip")
                
                hosts[host_name] = {
                    "ansible_host": host_ip,
                    "instance_id": instance.get("instance_id"),
                    "instance_state": instance.get("instance_state"),
                    "private_ip": instance.get("private_ip"),
                    "public_ip": instance.get("public_ip"),
                }
        
        return {
            "all": {
                "hosts": hosts,
                "vars": group_vars["all"]
            }
        }
    
    def get_host(self, hostname):
        """Return specific host variables"""
        all_hosts = self.get_all_hosts()
        
        if hostname in all_hosts["all"]["hosts"]:
            return all_hosts["all"]["hosts"][hostname]
        
        return {}
    
    def json_output(self):
        """Output inventory in JSON format for Ansible"""
        inventory = self.get_all_hosts()
        print(json.dumps(inventory, indent=2))
    
    def host_output(self, hostname):
        """Output host variables in JSON format"""
        host_vars = self.get_host(hostname)
        print(json.dumps(host_vars, indent=2))


def main():
    parser = argparse.ArgumentParser(
        description='Ansible Dynamic Inventory Script'
    )
    parser.add_argument('--list', action='store_true', 
                        help='List all hosts')
    parser.add_argument('--host', type=str, 
                        help='Get host variables')
    parser.add_argument('--inventory-file', type=str, 
                        help='Path to inventory.json file')
    
    args = parser.parse_args()
    
    # Initialize inventory
    inventory = DynamicInventory(inventory_file=args.inventory_file)
    
    # Handle requests
    if args.list:
        inventory.json_output()
    elif args.host:
        inventory.host_output(args.host)
    else:
        # Default to list if no arguments
        inventory.json_output()


if __name__ == '__main__':
    main()
